# Generated by Django 2.2.3 on 2019-07-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='cd',
            name='type',
        ),
        migrations.AddField(
            model_name='cd',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cd_library.Types'),
            preserve_default=False,
        ),
    ]
