# Generated by Django 2.2.3 on 2019-07-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_library', '0002_auto_20190710_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='type',
        ),
        migrations.AddField(
            model_name='cd',
            name='type',
            field=models.ManyToManyField(to='cd_library.Types'),
        ),
    ]
